apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "led-sniffer.fullname" . }}
  labels:
    app: {{ include "led-sniffer.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "led-sniffer.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "led-sniffer.fullname" . }}
    spec:
      affinity:
        nodeAffinity:
{{ toYaml .Values.global.nodeAffinity | indent 10 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      containers:
        - name: led-sniffer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            privileged: {{ .Values.privileged }}
          env:
            - name: PORT
              value: "{{ .Values.port }}"
            - name: THRESHOLD
              value: "{{ .Values.threshold }}"
            - name: DELAY
              value: "{{ .Values.delay }}"
          args:
            {{- if .Values.verbose }}
            - "--verbose"
            {{- end }} 

            {{- if .Values.source }}
            - "--source"
            - "{{ .Values.source }}"
            {{- end }}

            {{- if .Values.port }}
            - "--port"
            - "{{ .Values.port }}"
            {{- end }} 

            {{- if .Values.interface }} 
            - "--interface"
            - "{{ .Values.interface }}"
            {{- end}}

            {{- if .Values.threshold }}
            - "--threshold"
            - "{{ .Values.threshold }}"
            {{- end }} 

            {{- if .Values.delay }}
            - "--delay"
            - "{{ .Values.delay }}"
            {{- end }} 

            {{- if .Values.led_count }}
            - "--led-count"
            - "{{ .Values.led_count }}"
            {{- end }} 

            {{- if .Values.led_pin }}
            - "--led-pin"
            - "{{ .Values.led_pin }}"
            {{- end }} 

            {{- if .Values.animation_color }}
            - "--animation-color"
            - "{{ .Values.animation_color }}"
            {{- end }}

            {{- if .Values.animation_speed }}
            - "--animation-speed"
            - "{{ .Values.animation_speed }}"
            {{- end }} 

            {{- if .Values.animation_spacing }}
            - "--animation-spacing"
            - "{{ .Values.animation_spacing }}"
            {{- end }}

            {{- if .Values.animation_duration }}
            - "--animation-duration"
            - "{{ .Values.animation_duration }}"
            {{- end }} 

          volumeMounts:
            {{- range .Values.devices }}
            - name: {{ .name }}
              mountPath: {{ .hostPath }}
            {{- end }}
      volumes:
        {{- range .Values.devices }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            {{- if .type }}
            type: {{ .type }}
            {{- end}}
        {{- end }}
      restartPolicy: Always
