apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "led-sniffer.fullname" . }}
  labels:
    app: {{ include "led-sniffer.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "led-sniffer.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "led-sniffer.fullname" . }}
    spec:
      affinity:
        nodeAffinity:
{{ toYaml .Values.global.nodeAffinity | indent 10 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      containers:
        - name: led-sniffer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            privileged: {{ .Values.privileged }}
          args:
            {{- if .Values.verbose }}
            - "--verbose"
            {{- end }}
            {{- if .Values.source }}
            - "--source" 
            - "{{ .Values.source }}"
            {{- end }}
            - "--port" 
            - "{{ .Values.port }}"
            {{- if .Values.interface }}
            - "--interface" 
            - "{{ .Values.interface }}"
            {{- end }}
            - "--threshold" 
            - "{{ .Values.threshold }}"
            - "--delay" 
            - "{{ .Values.delay }}"
            - "--filter_size"
            - "{{ .Values.filter_size }}"
            - "--led-count"
            - "{{ .Values.led_count }}"
            - "--led-pin"
            - "{{ .Values.led_pin }}"
            - "--animation-color"
            - "{{ .Values.animation_color }}"
            - "--animation-speed"
            - "{{ .Values.animation_speed }}"
            - "--animation-spacing"
            - "{{ .Values.animation_spacing }}"
            - "--animation-duration"
            - "{{ .Values.animation_duration }}"
          volumeMounts:
            {{- range .Values.devices }}
            - name: {{ .name }}
              mountPath: {{ .hostPath }}
            {{- end }}
      volumes:
        {{- range .Values.devices }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            {{- if .type }}
            type: {{ .type }}
            {{- end}}
        {{- end }}
      restartPolicy: Always
