apiVersion: v2
name: neonswarm
description: Umbrella chart for all neonswarm micro-apps
type: application
version: 1.0.0
kubeVersion: ">=1.20.0-0"
dependencies:
  - name: led-sniffer
    version: 1.0.0
    repository: "file://charts/led-sniffer"
    condition: led-sniffer.enabled
  - name: lcd-storage
    version: 1.0.0
    repository: file://charts/lcd-storage
    condition: lcd-storage.enabled
  - name: agent
    version: 1.0.0
    repository: file://charts/agent
    condition: swarm.enabled
