{{- range .Values.swarm.agents }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .name }}-data"
spec:
  capacity:
    storage: 100G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data/agent
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .nodeName }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .name }}-data-volume"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
  volumeName: "{{ .name }}-data"
{{- end }}
