image:
  repository: cubbit/neonswarm-led-sniffer
  tag: latest
  pullPolicy: Always

source: 192.168.1.101
port: 9171
threshold: 1K
delay: 3.0
interface: ""
verbose: false

hostNetwork: true
privileged: true

imagePullSecrets:
  - name: regcred

devices:
  - name: gpiomem
    hostPath: /dev/gpiomem
  - name: spidev
    hostPath: /dev/spidev10.0

resources: {}

