apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lcd-storage-reader
  namespace: neonswarm
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: 
      - get
      - list
      - watch

